apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-mysql-pvc
  namespace: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
