apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  username: YWRtaW4=   # base64 encoded string for "admin"
  password: cGFzc3dvcmQ=   # base64 encoded string for "password"
